export const DATA = [
  {
    id: 1,
    name: "Leanne Graham",
    mail: "Sincere@april.biz",
    phoneNumber: "1-770-736-8031 x56442",
    site: "http://hildegard.org",
    liked: false,
  },
  {
    id: 2,
    name: "Ervin Howell",
    mail: "Shanna@melissa.tv",
    phoneNumber: "010-692-6593 x09125",
    site: "http://anastasia.net",
    liked: false,
  },
  {
    id: 3,
    name: "Clementine Bauch",
    mail: "Nathan@yesenia.net",
    phoneNumber: "1-463-123-4447",
    site: "http://ramiro.info",
    liked: false,
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    mail: "Julianne.OConner@kory.org",
    phoneNumber: "493-170-9623 x156",
    site: "http://kale.biz",
    liked: false,
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    mail: "Lucio_Hettinger@annie.ca",
    phoneNumber: "(254)954-1289",
    site: "http://demarco.info",
    liked: false,
  },
  {
    id: 6,
    name: "Mrs. Dennis Schulist",
    mail: "Karley_Dach@jasper.info",
    phoneNumber: "1-477-935-8478 x6430",
    site: "http://ola.org",
    liked: false,
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    mail: "Telly.Hoeger@billy.biz",
    phoneNumber: "210.067.6132",
    site: "http://elvis.io",
    liked: false,
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    mail: "Sherwood@rosamond.me",
    phoneNumber: "586.493.6943 x140",
    site: "http://jacynthe.com",
    liked: false,
  },
  {
    id: 9,
    name: "Glenna Reichert",
    mail: "Chaim_McDermott@dana.io",
    phoneNumber: "(775)976-6794 x41206",
    site: "http://conrad.com",
    liked: false,
  },
  {
    id: 10,
    name: "Clementina DuBuque",
    mail: "Rey.Padberg@karina.biz",
    phoneNumber: "024-648-3804",
    site: "http://ambrose.net",
    liked: false,
  },
];
